name: Lint

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/black.yml'
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/black.yml'

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black

      - name: Run tests
        run: |
          python -m black --check .